name: CO main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  docker-image-backend: ${{ secrets.DOCKER_IMAGE_BACKEND }}
  docker-image-frontend: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
  kube_config: "${{ secrets.KUBE_CONFIG }}"
on: 
  push:
    branches:
      - co-for-main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .

  publish-images:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: docker auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: "${{ secrets.DOCKER_IMAGE_BACKEND }}:${{ github.sha }}"
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: "${{ secrets.DOCKER_IMAGE_FRONTEND }}:${{ github.sha }}"
  deployment:
    needs: publish-images
    runs-on: ubuntu-latest
    steps:
      - name: Make .kube dir
        run: mkdir ./.kube
        #working-directory: .
      - name: Get kubeconfig contents
        run: echo "$kube_config" > ./config.txt 
        env:
          kube_config: ${{ secrets.KUBE_CONFIG }}
      - name: catting config
        run: cat ./config.txt
      - name: Decode kubeconfig
        run: cat ./config.txt | base64 -d > ./.kube/config
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
      - name: alter deployment yaml file
          run: grep -rl 'frontend:.*' ./frontend/frontend-deployment.yaml | xargs sed -i 's/frontend:.*/frontend:/g'    
      - name: more altering
        run: sed -i '/frontend:/s/$/${{ github.sha }}/' ./frontend/frontend-deployment.yaml
#      - name: Set new backend image
#        run: kubectl --kubeconfig=./.kube/config set image backend=${{ secrets.DOCKER_IMAGE_BACKEND }}:${{ github.sha }} -f ./backend/backend-deployment.yaml 
#        env:
#          docker-image-backend: ${{ secrets.DOCKER_IMAGE_BACKEND }} 
#      - name: Set new frontend image
#        run: kubectl --kubeconfig=./.kube/config set image frontend=${{ secrets.DOCKER_IMAGE_FRONTEND }}:${{ github.sha }} -f ./frontend/frontend-deployment.yaml
#        env:
#          docker-image-frontend: ${{ secrets.DOCKER_IMAGE_FRONTEND }}