name: GO CI
on: 
  push:
    branches:
      - ci-for-dev
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: build frontend
        run: cd frontend/ && go build
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: .
  test-code:
      runs-on: ubuntu-latest
      container: golang:latest
      steps:
        - name: download-artifact
          uses: actions/download-artifact@v2
          with:
            name: app
            path: .
        - name: test main.go 
          run: go test
          