name: GO CI
on: 
  push:
    branches:
      - dev
jobs:
  test-code:
      runs-on: ubuntu-latest
      container: golang:latest
      steps:
        - uses: actions/checkout@v2
        - run: cd frontend/
        - name: test main.go 
          run: go test
          